/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package rhcad.touchvg.core;

public class RecordPartData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RecordPartData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RecordPartData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        touchvgJNI.delete_RecordPartData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTick(int value) {
    touchvgJNI.RecordPartData_tick_set(swigCPtr, this, value);
  }

  public int getTick() {
    return touchvgJNI.RecordPartData_tick_get(swigCPtr, this);
  }

  public void setBeginStep(int value) {
    touchvgJNI.RecordPartData_beginStep_set(swigCPtr, this, value);
  }

  public int getBeginStep() {
    return touchvgJNI.RecordPartData_beginStep_get(swigCPtr, this);
  }

  public void setEndStep(int value) {
    touchvgJNI.RecordPartData_endStep_set(swigCPtr, this, value);
  }

  public int getEndStep() {
    return touchvgJNI.RecordPartData_endStep_get(swigCPtr, this);
  }

  public RecordPartData() {
    this(touchvgJNI.new_RecordPartData(), true);
  }

}
